### PR TITLE
Adding Ghana geojson

### PR DESCRIPTION
**Pull request by karimkawambwa**
### Ghana Geo Data

- The data was obtained from https://data.gov.gh/dataset/shapefiles-all-districts-ghana-170-districts
- The data was uploaded and split accordingly using mapshaper https://mapshaper.org/
- Using js, the properties were added to the districts

```
const fs = require("fs");
const file = "./western.json";
const json = JSON.parse(fs.readFileSync(file));
function titleCase(str) {
    return str.toLowerCase().split(' ').map(function(word) {
        if (word) {
            return word.replace(word[0], word[0].toUpperCase());
        }
        return '';
    }).join(' ');
  }
json.features.forEach(({ properties }) => {
    delete properties["split_id"];
    properties["code"] = "GH_031_" + properties["DIST_CODE"] ;
    properties["level"] = "district";
    properties["geoid"] = "district_" + properties["code"];
    properties["name"] = titleCase(properties["DISTRICT"]);
});
fs.writeFileSync(file, JSON.stringify(json, null, 2));
```

### CODE REVIEW

**Comment by karimkawambwa** [comment]
Closing this in favor of change made by @KhadijaMahanga  in https://github.com/CodeForAfrica/mapit

Documentation will be made there once the local changes are pushed
@kilemensi should this repo be deleted or made private since its not ready or being used ?

**Comment by kilemensi** [comment]
> Closing this in favor of change made by @KhadijaMahanga in https://github.com/CodeForAfrica/mapit
> 
> Documentation will be made there once the local changes are pushed
> @kilemensi should this repo be deleted or made private since its not ready or being used ?

Yeah, once we've switched to using `CfA/mapit` repo (I believe the current running `mapit` instance is still using code from this repo), _then_ we can take this repo private @karimkawambwa ...

**Comment by karimkawambwa** [comment]
> > Closing this in favor of change made by @KhadijaMahanga in https://github.com/CodeForAfrica/mapit
> > Documentation will be made there once the local changes are pushed
> > @kilemensi should this repo be deleted or made private since its not ready or being used ?
> 
> Yeah, once we've switched to using `CfA/mapit` repo (I believe the current running `mapit` instance is still using code from this repo), _then_ we can take this repo private @karimkawambwa ...

@kilemensi

@KhadijaMahanga said that the current deployed mapit is running `CfA/mapit` not this code.

**Comment by kilemensi** [comment]
> @kilemensi
> 
> > Yeah, once we've switched to using `CfA/mapit` repo (I believe the current running `mapit` instance is still using code from this repo), _then_ we can take this repo private @karimkawambwa ...
> 
> @KhadijaMahanga said that the current deployed mapit is running `CfA/mapit` not this code.

Then you no longer need me here... You're both admins on this repo so you should be able to take it private @karimkawambwa / @KhadijaMahanga

**Pull request closed without merging**
